name: Build & Lint CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-api
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './backend-api/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint Next.js
        run: npm run lint
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Build Next.js
        run: npm run build

  lint-and-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend-client
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './frontend-client/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Lint Vite App
        run: npm run lint
      - name: Type Check
        run: npm run type-check
      - name: Build Vite App
        run: npm run build
